### ISSUE TITLE
Clean up search in header bar

### ISSUE THREAD

**Issue by aembler** [concrete5/brand_central#28]
The search field added to the header bar works and appears to submit the correct location, but the header's design is pretty far from the way the comp is supposed to look. Please make it match the comp, including the position/spacing between the navigation labels, the height of the search bar, any border color/text color of the search field, etc...

Current state in the repo:

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/527809/94950668-d7adda80-0497-11eb-9774-58a8305442eb.png">

Original comp:

![](https://user-images.githubusercontent.com/527809/93162257-3d911880-f6c9-11ea-9975-5621a8ca8bb6.png)

**Comment by bitterdev** [comment]
Believe me or not. I know that you will tell me that you don't like the nav bar implementation because i don't like the nav bar by my own. But i have tried to find a good compromise between usability and design. 

The reason for why i have changed the main nav in compare to the comp is because the menu items breaks into a second line because the space is not enough for the items.

The smallest desktop view starts at a width from 992px. The logo area has a fixed width incl. padding of 243px. The search bar in the layout has a total width incl. the border of 303px. We also need a spacing between the search bar and the menu container of 15px. So the rest width at the lowest break point for the entire menu container is 431px.

One menu item has a fixed width of 135px in the current implementation. Means you can place exactly 3 menu items nicely into the layout. But if you have one more the menu will looks destroyed at the smallest possible viewport.

If you perform the standard installation with sample content you have 5 menu items:

1) Print & Web Materials
2) Photo Gallery
3) Branding Guidelines
4) Market Research
5) Sponsorship

My aim was to use a combination of flex containers with one fixed width item and the css property text-overflow ellipsis to short the text of the menu items if required. Because this techniques wasn't enough anyway to display 5 menu items i also decreased the size of the search bar.

What i can do alternate is to rollback the css menu changes, set the search bar to 303px like in the comp and use overflow: hidden property for the menu container to prevent ugly line breaks. But the downside is that it will cut off any additional menu items when the viewport is to small.

Another option is to increase the breakpoint for the mobile nav or change the entire navigation to use a hamburger menu in all sizes and take use of a vertical nav. This trend is going to be more popular in web development because sites are getting more and more content over the time.

Or what you have for ideas for the implementation of the menubar ? I wan't to prevent usability issues by cutting of menu items.

**Comment by aembler** [comment]
I understand that, and probably some of this has to do with miscommunication regarding the sample content and the way the current site works today. The main BC site doesn't have five menu items, it has only three, as reflected in the designs I pasted above. It's way more important that those three nav items look good and don't truncate with overflow ellipses than the navigation support more than three elements. Additionally we need to make sure the search looks like the comp (and it doesn't quite match up either.)

I think we should support the designs that we have as closely as possible, and then if sites that use BC need to override that CSS in order to make their use cases work, they can add in custom CSS to support more nav items.

**Comment by bitterdev** [comment]
Okay understand. Will provide an Update soon.

**Comment by aembler** [comment]
Thanks!

**Comment by aembler** [comment]
looks good!
