### ISSUE TITLE
Can we get analytics to be file based instead of asset based?

### ISSUE THREAD

**Issue by aembler** [concrete5/brand_central#37]
Right now we have custom `gtag` methods that track asset downloads on download single pages (just search the code base for `gtag`). Unfortunately this is tracking asset, not file ID, so it's not useful for us because we don't know which file the user is downloaded most of out of an asset.

can we track against file ID as well? Also can we pass any other meta data to gtag? I'm not really familiar with what's possible there but passing file ID and URL/name might be nice, if  it's something gtag supports.

**Comment by bitterdev** [comment]
Google allows for custom gtag events like in the current implementation only to pass nummeric values (see https://developers.google.com/analytics/devguides/collection/gtagjs/events, https://support.google.com/analytics/answer/1033068#Anatomy).

So what i can do is to add more gtag event calls with the file id (one for each file). So it is possible to get analytics of the file by it's id. But tracking URL/name or other meta data is not possible because of Google Limitation.

Please give me approval if it's enough add the file id's without it's meta data.

**Comment by jessicadunbar** [comment]
I have Google Tag Manager running, @bitterdev ID tracking will work too.  Instead of passing a numeric value I set up variables to track the click text and push the click text into analytics for for individual file tracking. 
![View_Asset____MWR_Brand_Central](https://user-images.githubusercontent.com/1581195/96162140-2fabfe80-0ee6-11eb-893f-d5642e8a8104.jpg)

**Comment by fmaruna** [comment]
So we're good here, call this done.
