### ISSUE TITLE
Redirect user to page you were on instead of home page when editing a collections. 

### ISSUE THREAD

**Issue by aembler** [concrete5/brand_central#39]
When you edit a collection and save, it dumps you to main search instead of the collection you were on. This is super annoying. Can it redirect you back to where you were (collection view) when you leave collection edit?

**Comment by bitterdev** [comment]
I can't reproduce this issue because there are no redirects that points to the main search?

These are all redirects of all controllers:

![Bildschirmfoto 2020-10-15 um 10 20 01](https://user-images.githubusercontent.com/15018219/96096321-02ecec80-0ed0-11eb-8280-93904e4fd977.png)

As you can see the user will be redirected always to the detail page if available. Only when deleting an item and it no longer exists it will redirects you to the parent page (like /collections for a collection item).

But there was an issue while starting edit mode of a collection, see here:

![Bildschirmfoto 2020-10-15 um 10 12 44](https://user-images.githubusercontent.com/15018219/96096358-0c765480-0ed0-11eb-9637-94d27c9a1153.png)

I have fixed this by changing line 115 to from `$form = $entity->getForm('Frontend');` to `$form = $entity->getForms()[0];`. I don't know if you have a Form called "Frontend" in the production environment but in the install data there is no form shipped called "Frontend". If you agree with this change i will commit this to the next PR.

**Comment by fmaruna** [comment]
yeah let me see if i can't get some more detail on this. i feel like were chasing ghosts..

**Comment by aembler** [comment]
Fabian - to fix the error that you're seeing above, you'll need to add another express form for the collection object. It has be named "Frontend". Just add a fieldset to it and add all the collection express attributes to it, and then it'll use that form when you hit the edit button on the frontend:

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/527809/96292099-e9b27180-0f9d-11eb-92da-e5196f574746.png">

**Comment by aembler** [comment]
Regarding the underlying issue described here, I can't reproduce it locally on my brandcentral install. I haven't tried on our stage.

**Comment by bitterdev** [comment]
I have change the code like described above to fix this. Hope thats okay? Btw. it's the same code like when adding a collection.
