### ISSUE TITLE
Bugs in Brandcentral File Picker

### ISSUE THREAD

**Issue by aembler** [concrete5/brand_central#50]
Getting some reports back from QA:

1. When you select BrandCentral in the file picker sidebar, you get a console error now:

![image](https://user-images.githubusercontent.com/527809/97236535-8812b400-17a2-11eb-819d-7373ef576559.png)

2. While searching BrandCentral from our site, we encountered timeouts frequently. We had someone try to search "jpg", which in our BrandCentral install will returns over 4000 results. Unfortunately it timed out, while the actual search results page of BrandCentral had no issue. I think this is because your assets search endpoint has no pagination support. Can you add pagination support using the pagination vue component we already have? 

3. All of the files in my search example have thumbnails (if you look on the brandcentral site I'm using as an example):

<img width="993" alt="image" src="https://user-images.githubusercontent.com/527809/97237264-091e7b00-17a4-11eb-8300-9f8787877fa7.png">

However, some of the files are broken in the file manager search results:

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/527809/97237294-1471a680-17a4-11eb-96a1-d7bebcd7e66f.png">

When I look at the image it's trying to load, it looks like the URL is malformed.

    https://mystage.brandcentral.comhttps//mystage.brandcentral.com/application/files/4615/4145/8321/153178.jpg

If you trim out the errant `https//mystage.brandcentral.com` from there it works.

4. I'm seeing duplicate search requests happening in the XHR panel in Chrome when I do a search. The search works (if it's small enough, if it's too big it times out due to the issues in number 2 above). However we should only do one search, because it's too resource intensive to do multiple. 

5. When I do select a valid file and attempt to import it, it used to work but now does not:

![image](https://user-images.githubusercontent.com/527809/97237485-74684d00-17a4-11eb-90fb-592e46cea105.png)

**Comment by bitterdev** [comment]
Because of pont number 3 i'm a little bit confused.

The thumbnail URL is generated by the existing AssetTransformer class, see:
https://github.com/concrete5/brand_central/blob/bef1e1662ab52748d4490b2904437326a164de33/src/AssetLibrary/API/V1/Transformer/AssetTransformer.php#L65

This should be fixed by removing the `$url . ` from line 65 but this can have negative side effects because there are other code occurrences that are take use of the generated thumbnail url like the asset uploader form react component.

Can you explain me the reason for why the canocial url is explicitly added to the thumbnail url? Was it maybe a hotfix for an old core bug?

I mean normally the core of concrete is returning valid url's with the domain name if you have enabled canocial url's in dashboard.

Otherwise i can implement a seperate AssetTransformer for the public api but that is redundant so better to fix this in general.

**Comment by bitterdev** [comment]
In general would it possible to get access to the staging area (c5 + FTP/SSH)? There are issues i can not reproduce on my local environment like 3 + 5. I can only guess. I assume that the file type isn't white listed or that the displayed file name doesn't contain a file type so that the importer class crashes and don't return a valid file version object and because of bad error reporting there comes the issue null given on entity manager.

**Comment by bitterdev** [comment]
Because of 4 i can't confirm that. If you change the file type a new search request is fired. But otherwise not. Search requests are only sent for one time when you change the search term and/or when you change the file type. When changing the file type the query terms are different but the base url is the same so maybe it looks like the same search result but it isn't...

I agree with 4k search results you will get a lot of performance issues. Therefore i had implemented the 3 characters limit in the first version to decrease the number of results as long as there is no pagination support.

I will work now on pagination support.

**Comment by bitterdev** [comment]
Point 1 is fixed, see https://github.com/concrete5/bedrock/pull/126

**Comment by bitterdev** [comment]
Okay i have added pagination support, see the PR's:

- https://github.com/concrete5/concrete5/pull/9173
- https://github.com/concrete5/brand_central/pull/52
- https://github.com/concrete5/brand_central_connector/pull/4

**Comment by aembler** [comment]
This is looking a lot better. I found one piece of strange behavior that's probably related to number 4. But this is looking a lot better so I'm going to close this and open a specific issue for that. Looking really close!
